### ISSUE TITLE
How can I modify tar.gz?

### ISSUE THREAD

**Issue by gloias** [mafintosh/tar-stream#121]
I want to modify a tar.gz file. I follow the procedure described in label "Modifying existing tarballs" but when my tar.gz is a little bigger(e.x. 20kb), it doesn't work. I noticed that every file of tar.gz is transferred to 'pack' and after some additions the pack memory is not enough to add the next files. How can I solve this problem?

**Comment by piranna** [comment]
You need to decompress, modify, and re-compress. Modify tarfiles also has a trick, because you can't modify in place, just only overwrite with zeroes and append, to actual modify it you need to rewrite it.

A different topic if Google `.gz.tar` format, where each file is compressed independently, it's not so much compressed but allow to easier access and modify them.
