### ISSUE TITLE
Make tar-stream a TransformStream

### ISSUE THREAD

**Issue by thlorenz** [mafintosh/tar-stream#14]
I mentioned this previously, but I'd like to be able to use tar-stream in this manner (or similar):

``` js
intar.pipe(tarStream(onentry, onfinish)).pipe(transformedTar)
```

I made a feeble attempt to get this to work outside of tar stream in [dockerify lazy-stream branch](https://github.com/thlorenz/dockerify/blob/lazy-stream/dockerify-readable.js), but had only mixed success.

The tests that all passed previously now only pass in `node 0.10`.
I hope though this can server as a start to figure out how the above could be achieved.

**Comment by malandrew** [comment]
@thlorenz can you go more into the use case?

**Comment by thlorenz** [comment]
Not sure what else to say, I think the use case example is pretty clear?

**Comment by wyvernnot** [comment]
I can share the use case I am currently woking on, it is related to docker build context.

In short words, you can post a tarball to docker daemon via [ Docker Remote API](https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.22.md#build-image-from-a-dockerfile)

**Requirement of tarball structure**

To make this work, the structure of tarball should be
```
Dockerfile
index.js
package.json
README.md
```

But, if you download any repository tarball from github, you will get a tarball like following structure:

```
master/Dockerfile
master/index.js
master/package.json
master/README.md
```

This tar ball can not be directly used to create Docker build context, because the extra folder called master

**Use tar-strim to fix it**

I wrote this package called [tar-strip](https://github.com/wyvernnot/tar-strip). It aligns with the simple principle of `tar-stream` that everything is stream.

The code looks like this:

```js
var downLoadRequest = request
  .get('https://github.com/wyvernnot/gitlab-webhook-receiver/archive/master.tar.gz');

var buildRequest = request
  .post('http://unix:/var/run/docker.sock:/build?nocache=true');

downLoadRequest
  .pipe(gunzip)
  .pipe(stripPack)
  .pipe(gzip)
  .pipe(buildRequest);

buildRequest.pipe(process.stdout);
```

**Comment by chpio** [comment]
yeah, i needed that functionality too, that's why i made the `tar-vinyl-stream` package, which consumes a tar stream and emits `vinyl`objects for each entry.

**Comment by piranna** [comment]
We should have here two transform objects, one for extract that consume a bytestream and emit `data` with stream objects, and another for pack that consume them and emit a bytestream. This probably would break API compatibility, so this should be a major version.

**Comment by mafintosh** [comment]
its an async iterator now
